config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
 
  #grab all notes (NOTE, for some reason, it follow by update, check order!)
 def index
  @posts = Post.all.order('id')
end

#grab one note
def show
  #@post = Post.find(params[:id])
end

#show the new view page
def new
  @post = Post.new
  render :_form
end

# create function for the new notes page
def create
    @post = Post.new(posts_params)
    if @post.save
      redirect_to posts_path
    else
      render :new #method to create
    end
end

def destroy #delete function, follow via Rails Route list
#binding.pry
  #Post.find(params[:id]).destroy
  @post.destroy
  redirect_to posts_path
end


def edit
render :_form
end

  # update/edit function for the edit notes page
  #find the note via its ID for edit
def update
  #@post = Post.find(params[:id])
  if @post.update(posts_params) #pass to the private below
    redirect_to posts_path
  else
    render :edit #method to update
  end
end

private

# this help the controller understand what the data is being entered
# into SQL database. Need to be in private
def set_post
  @post = Post.find(params[:id])
end

def posts_params
   params.require(:post).permit(:title, :color, :body)
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yellow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
  
<h1><%= @post.id ? "Edit #{@post.title}" : "Add New Post-It" %></h1>
<hr />
<%= form_with(model: @post, local: true) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, placeholder: "Title:" %>
    <%= f.label :body %>
    <%= f.text_field :body, required: true, placeholder: "Body:" %>
    <%= f.label :color %>
    <%= f.text_field :color, required: true, placeholder: "Color:" %>
  </div>
    <%= f.submit %>
<%end%>

app/views/posts/index.html.erb
<h1>Your Post-Its</h1>
<p>Find me in app/views/notes/index.html.erb</p>

<h1> Post-Its </h1>
<% @posts.each do |post| %>
<table  bgcolor='<%= post.color %>' ><tr><td>  
<h2><%= post.title %></h2><br>
<%= post.body %>
<%= post.color %>
  
  <%= link_to 'Show Post-It', post_path(post) %>
  <%= link_to 'Edit Post-It', edit_post_path(post) %>
  <%= link_to 'Destroy Post-It', post, method: :delete %>
</td></tr></table>
  <% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
  
<h1>Title: <%= @post.title %></h1>
<h2>Body: <%= @post.body %>
<h2>Color: <%= @post.color %>
<br />
<br />
<%= link_to "Edit Post", edit_post_path %>
<%= link_to "Delete Post", post_path(@post), method: :delete %>
<%= link_to "Back", posts_path %>